/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.h15_firstGUI.GUI;

import ec.edu.espe.h15_firstGUI.utils.FileManager;
import ec.edu.espe.h15_firstGUI.model.BarberShop;
import ec.edu.espe.h15_firstGUI.model.Employee;
import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.JTextField;

/**
 *
 * @author Miquely CalvopiÃ±a
 */
public class FrmNewEmployee extends javax.swing.JFrame {
   
    
    private char validate;
    private String auxStringInput = null;
    private String auxStringForFile = null;
    private boolean flag = false;
    private boolean icVerification = false;
    private boolean phoneVerification = false;
    private boolean ageVerification = false;
    private boolean salaryVerification = false;
    
    /**
     * Creates new form NuevoCliente
     */
    public FrmNewEmployee() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTittle = new javax.swing.JLabel();
        lblCI = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        lblFullName = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        lblPhoneNumber = new javax.swing.JLabel();
        lblSalary = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        txtCI = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        txtFullName = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtPhoneNumber = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        txtSalary = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        lblBackround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTittle.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        lblTittle.setForeground(new java.awt.Color(255, 255, 255));
        lblTittle.setText("INGRESE LOS DATOS DEL NUEVO EMPLEADO");
        getContentPane().add(lblTittle, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, -1, -1));

        lblCI.setForeground(new java.awt.Color(255, 153, 0));
        lblCI.setText("Número de cédula:");
        getContentPane().add(lblCI, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        lblID.setForeground(new java.awt.Color(255, 153, 0));
        lblID.setText("Id:");
        getContentPane().add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        lblFullName.setForeground(new java.awt.Color(255, 153, 0));
        lblFullName.setText("Nombre completo:");
        getContentPane().add(lblFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        lblAge.setForeground(new java.awt.Color(255, 153, 0));
        lblAge.setText("Edad:");
        getContentPane().add(lblAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, -1));

        lblPhoneNumber.setForeground(new java.awt.Color(255, 153, 0));
        lblPhoneNumber.setText("Teléfono:");
        getContentPane().add(lblPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, -1));

        lblSalary.setForeground(new java.awt.Color(255, 153, 0));
        lblSalary.setText("Sueldo:");
        getContentPane().add(lblSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, -1, -1));

        lblAddress.setForeground(new java.awt.Color(255, 153, 0));
        lblAddress.setText("Dirección:");
        getContentPane().add(lblAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, -1, -1));

        txtCI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCIKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCIKeyTyped(evt);
            }
        });
        getContentPane().add(txtCI, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 290, 30));
        getContentPane().add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 290, 30));

        txtFullName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFullNameKeyTyped(evt);
            }
        });
        getContentPane().add(txtFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 290, 30));

        txtAge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAgeKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAgeKeyTyped(evt);
            }
        });
        getContentPane().add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 290, 30));

        txtPhoneNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPhoneNumberKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPhoneNumberKeyTyped(evt);
            }
        });
        getContentPane().add(txtPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 290, 30));

        btnSave.setBackground(new java.awt.Color(0, 0, 0));
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Guardar");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 460, -1, -1));

        btnClose.setBackground(new java.awt.Color(0, 0, 0));
        btnClose.setForeground(new java.awt.Color(255, 255, 255));
        btnClose.setText("Regresar");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 460, -1, -1));

        txtSalary.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSalaryKeyTyped(evt);
            }
        });
        getContentPane().add(txtSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 290, 30));

        txtAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAddressKeyTyped(evt);
            }
        });
        getContentPane().add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, 290, 30));

        lblBackround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/espe/BarberShop/GUI/components/BarberShopWallpaperLoging_1.jpg"))); // NOI18N
        lblBackround.setPreferredSize(new java.awt.Dimension(650, 510));
        getContentPane().add(lblBackround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
       
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try {
            Employee person = new Employee();
            BarberShop barber = new BarberShop();
            FileManager file = new FileManager();
            icVerification = person.ICVerification(txtCI, person);
            phoneVerification = person.PhoneVerification(txtPhoneNumber, person);
            ageVerification = person.AgeVerification(txtAge, person);
            salaryVerification = person.SalaryVerification(txtSalary, person);
            
            person.setIdentifyCardNumber(txtCI.getText());
            person.setFullName(txtFullName.getText());
            person.setAge(Integer.parseInt(txtAge.getText()));
            person.setSalary(Double.parseDouble(txtSalary.getText()));
            person.setAddress(txtAddress.getText());
            person.setPhoneNumber(txtPhoneNumber.getText());
            person.setId(txtID.getText());
            String ifexists = txtCI.getText();
            flag = file.search("Empleados.csv", ifexists);
            if(flag == true){
                System.out.println("si existe");
            }else{
                System.out.println("no existe");
            }
            if(icVerification == true){
                if(phoneVerification ==true){
                    if(ageVerification ==true){
                        if(salaryVerification ==true){
                            if(flag == false){
                                auxStringForFile = person.toString(person);
                                showMessageDialog(null, "Empleado aÃ±adido");
                                try {
                                    barber.newEmployee(auxStringForFile);
                                    
                                } catch (IOException ex) {
                                    Logger.getLogger(FrmNewEmployee.class.getName()).log(Level.SEVERE, null, ex);
                                }
                                
                            }else{
                                showMessageDialog(null, "El empleado ya existe en el archivo");
                            }
                        }else{
                            showMessageDialog(null, "Datos erroneos, vuelva a ingresar");
                        }
                    }else{
                        showMessageDialog(null, "Datos erroneos, vuelva a ingresar");
                    }
                }else{
                    showMessageDialog(null, "Datos erroneos, vuelva a ingresar");
                }
            }else{
                showMessageDialog(null, "Datos erroneos, vuelva a ingresar");
            }
        } catch (IOException ex) {
            Logger.getLogger(FrmNewEmployee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtCIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCIKeyTyped
        validationOfNumbers(txtCI);
        int limit = 10;
        if (txtCI.getText().length()==limit){
            evt.consume();
        }
    }//GEN-LAST:event_txtCIKeyTyped

    private void txtCIKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCIKeyPressed
    }//GEN-LAST:event_txtCIKeyPressed

    private void txtFullNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFullNameKeyTyped
        validate = evt.getKeyChar();
        validationOfLetters(validate,txtFullName);
    }//GEN-LAST:event_txtFullNameKeyTyped

    private void txtAgeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAgeKeyTyped
       validate = evt.getKeyChar();
       validationOfNumbers(txtAge);
    }//GEN-LAST:event_txtAgeKeyTyped

    private void txtPhoneNumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhoneNumberKeyTyped
        validationOfNumbers(txtPhoneNumber);
        int limit = 10;
        if (txtPhoneNumber.getText().length()==limit){
            evt.consume();
        }
    }//GEN-LAST:event_txtPhoneNumberKeyTyped

    private void txtPhoneNumberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhoneNumberKeyPressed
    }//GEN-LAST:event_txtPhoneNumberKeyPressed

    private void txtAgeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAgeKeyPressed
    }//GEN-LAST:event_txtAgeKeyPressed

    private void txtAddressKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAddressKeyTyped
        validate = evt.getKeyChar();
        validationOfLetters(validate,txtAddress);
    }//GEN-LAST:event_txtAddressKeyTyped

    private void txtSalaryKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSalaryKeyTyped
        validate = evt.getKeyChar();
        this.validationOfNumbers(txtSalary);
    }//GEN-LAST:event_txtSalaryKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmNewEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmNewEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmNewEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmNewEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmNewEmployee().setVisible(true);
            }
        });
    }
    
    public void validationOfNumbers(JTextField nameOfTheTextField)
    {
        auxStringInput = nameOfTheTextField.getText();
        try
        {
            double auxForVerification = Double.parseDouble(auxStringInput);
            nameOfTheTextField.setBackground(Color.WHITE);
        }
        catch (NumberFormatException exc)
        {
            nameOfTheTextField.setBackground(Color.red);
        }
    }
    public void validationOfLetters(char charValidation, JTextField nameOfTheTextField)
    {
        if(Character.isDigit(charValidation))
        {
            getToolkit().beep();
            nameOfTheTextField.setBackground(Color.red);
        }
        else
        {
            nameOfTheTextField.setBackground(Color.WHITE);
            
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblBackround;
    private javax.swing.JLabel lblCI;
    private javax.swing.JLabel lblFullName;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblPhoneNumber;
    private javax.swing.JLabel lblSalary;
    private javax.swing.JLabel lblTittle;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtCI;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtSalary;
    // End of variables declaration//GEN-END:variables
}
