/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.GUI;

/**
 *
 * @author G403
 */
public class frmMainMenu extends javax.swing.JFrame {

    /**
     * Creates new form frmMainMenu
     */
    public frmMainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mnuBarra = new javax.swing.JMenuBar();
        mnuProject = new javax.swing.JMenu();
        mnuAcercaDE = new javax.swing.JMenu();
        mnuSistema = new javax.swing.JMenuItem();
        mnuLicencia = new javax.swing.JMenuItem();
        mnuCopyright = new javax.swing.JMenuItem();
        mnuProducto = new javax.swing.JMenu();
        mnuAñadir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mnuProject.setText("BarberShop Project");

        mnuAcercaDE.setText("Acerca de ...");

        mnuSistema.setText("Mi sistema");
        mnuAcercaDE.add(mnuSistema);

        mnuLicencia.setText("Mi licencia");
        mnuAcercaDE.add(mnuLicencia);

        mnuCopyright.setText("Copyriht");
        mnuAcercaDE.add(mnuCopyright);

        mnuProject.add(mnuAcercaDE);

        mnuBarra.add(mnuProject);

        mnuProducto.setText("Producto");

        mnuAñadir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        mnuAñadir.setText("Añadir");
        mnuAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAñadirActionPerformed(evt);
            }
        });
        mnuProducto.add(mnuAñadir);

        mnuBarra.add(mnuProducto);

        setJMenuBar(mnuBarra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAñadirActionPerformed
         FrmAddProduct frmAddProduct = new FrmAddProduct();
        frmAddProduct.setVisible(true);
        
    }//GEN-LAST:event_mnuAñadirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu mnuAcercaDE;
    private javax.swing.JMenuItem mnuAñadir;
    private javax.swing.JMenuBar mnuBarra;
    private javax.swing.JMenuItem mnuCopyright;
    private javax.swing.JMenuItem mnuLicencia;
    private javax.swing.JMenu mnuProducto;
    private javax.swing.JMenu mnuProject;
    private javax.swing.JMenuItem mnuSistema;
    // End of variables declaration//GEN-END:variables
}
